# Site settings
# title: Clean Blog
# header-img: img/home-bg.jpg
# email: your-email@yourdomain.com
# description: "Write your site description here. It will be used as your sites meta description as well!"
# baseurl: "/universityofprofessorex-blog-jekyll"
# url: "http://yourdomain.com"
# twitter_username: SBootstrap
# github_username:  davidtmiller
# facebook_username:  IronSummitMedia

# # Build settings
# markdown: kramdown
# highlighter: pygments
# permalink: pretty
# paginate: 5
# exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title:            University of ProfessorEX
tagline: LORD 7th THE MEMEKAGE
email: professorex.university@gmail.com
# header-img:       img/home-bg.jpg
description: > # this means to ignore newlines until "baseurl:"
  â„™ğ•£ğ• ğ•—ğ•–ğ•¤ğ•¤ğ• ğ•£ ğ”¼ğ•© ğ•„ğ•–ğ•ğ•–s
author:             iamprofessorex
# baseurl:            "/universityofprofessorex-blog"
baseurl:            "/blog"
# url:                "https://universityofprofessorex.github.io"


# baseurl: "" # the subpath of your site, e.g. /blog
#Your site's domain goes here. Leave localhost server or blank when working locally.
# url: "https://iamprofessorex.com" # the base hostname & protocol for your site, e.g. http://example.com
url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: iamprofessorex
github_username:  iamprofessorex
facebook_username:  iamprofessorex
instagram_username:  iamprofessorex
linkedin_username:


# # Build settings
# markdown: kramdown
# theme: minima
# plugins:
#   - jekyll-feed

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
# paginate_path:      "/posts/page:num/"
paginate_path:      "/blog/:year/:month/:day/:title/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

exclude: [ ".vscode" ]
