# Site settings
title:            "University of ProfessorEX"
tagline: "LORD 7th THE MEMEKAGE"
email: "professorex.university@gmail.com"
encoding: UTF-8
# header-img:       img/home-bg.jpg
description: > # this means to ignore newlines until "baseurl:"
  â„™ğ•£ğ• ğ•—ğ•–ğ•¤ğ•¤ğ• ğ•£ ğ”¼ğ•© ğ•„ğ•–ğ•ğ•–s
author:             iamprofessorex
# baseurl:            "/universityofprofessorex-blog"
baseurl:            "/blog"
# url:                "https://universityofprofessorex.github.io"


# baseurl: "" # the subpath of your site, e.g. /blog
#Your site's domain goes here. Leave localhost server or blank when working locally.
url: "https://iamprofessorex.com" # the base hostname & protocol for your site, e.g. http://example.com
# url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: iamprofessorex
github_username:  iamprofessorex
facebook_username:  iamprofessorex
instagram_username:  iamprofessorex
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
# paginate_path:      "/posts/page:num/"
paginate_path:      "/blog/:year/:month/:day/:title/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

exclude: [ ".vscode" ]
