# Site settings
title:            "University of ProfessorEX"
tagline: "LORD 7th THE MEMEKAGE"
email: "professorex.university@gmail.com"
encoding: UTF-8
# header-img:       img/home-bg.jpg
description: > # this means to ignore newlines until "baseurl:"
  â„™ğ•£ğ• ğ•—ğ•–ğ•¤ğ•¤ğ• ğ•£ ğ”¼ğ•© ğ•„ğ•–ğ•ğ•–s
author:             iamprofessorex
# baseurl:            "/universityofprofessorex-blog"
baseurl:            "/"

# baseurl: "" # the subpath of your site, e.g. /blog
#Your site's domain goes here. Leave localhost server or blank when working locally.
# the base hostname & protocol for your site, e.g. http://example.com
url: "http://iamprofessorex.com"
twitter_username: iamprofessorex
github_username:  iamprofessorex
facebook_username:  iamprofessorex
instagram_username:  iamprofessorex
linkedin_username:

# Add your google-analytics ID here to activate google analytics
# out your google-analytics code
google_analytics:   UA-XXXXXXXXX-X

# Build settings
markdown:           kramdown
paginate:           5
highlighter: rouge
# paginate_path:      "/posts/page:num/"
paginate_path:      "/blog/:year/:month/:day/:title/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

exclude: [ ".vscode" ]

# SOURCE: https://github.com/json-api/json-api/blob/gh-pages/_config.yml
# url: http://jsonapi.org
# source: .
# destination: ./public

# # github pages we cannot customize
# lsi: false
# whitelist:
#   - jekyll-coffeescript
#   - jekyll-gist
#   - jekyll-paginate
#   - jekyll-redirect-from
#   - jekyll-mentions
#   - jekyll-sitemap
#   - jekyll-feed
#   - jekyll-seo-tag
#   - jemoji
# incremental: false
# gist:
#   noscript: false

# # customize github pages
# quiet: false
# markdown: kramdown
# highlighter: rouge
# kramdown:
#   input: GFM
#   hard_wrap: false
#   auto_ids: true
#   auto_id_prefix: auto-id-
#   auto_id_stripping: true
#   template: '' # cannot customize
#   math_engine: mathjax # cannot customize
#   syntax_highligher: rouge # cannot customize

# plugins:
#   - jekyll-redirect-from

# exclude:
#   - Rakefile
#   - README.md
#   - Gemfile
#   - Gemfile.lock
#   - CNAME
#   - .gitignore
#   - ./public
#   - ./stylesheets/*.scss

# port: 9876

# collections:
#   format:
#     output: true
#   errors:
#     output: true
#   profiles:
#     output: true
#     permalink: /:collection/:path

# defaults:
#   - scope:
#       path: ""
#       type: format
#     values:
#       layout: page
#       show_sidebar: true
#       is_spec_page: true
#   - scope:
#       path: ""
#       type: "profiles"
#     values:
#       layout: error
#       is_spec_page: false
#       show_sidebar: false
#   - scope:
#       path: ""
#       type: "errors"
#     values:
#       layout: error
#       is_spec_page: false
#       show_sidebar: false
#   - scope:
#       path: "*/*/*/index.md"
#       type: "profiles"
#     values:
#       layout: profile
#       is_spec_page: false
#       show_sidebar: true

# latest_version: 1.0
# excerpt_separator: ""
# announcement: ""

# navigation:
# - title: JSON API
#   url: /
# - title: Specification
#   url: /format/
# - title: Extensions
#   url: /extensions/
# - title: Recommendations
#   url: /recommendations/
# - title: Examples
#   url: /examples/
# - title: Implementations
#   url: /implementations/
# - title: FAQ
#   url: /faq/
# - title: About
#   url: /about/

# quicklinks:
# - title: View the specification
#   url: /format/
# - title: Contribute on GitHub
#   url: https://github.com/json-api/json-api

# profile_categories:
#   - Pagination
#   # these are some other potential categories.
#   # Uncomment them if you're adding a profile in one of these categories.
#   # - Filtering
#   # - Actions/Hypermedia
#   # - Data Modeling
#   # - Deep Querying
